version: "3.6"
services:
 
  rest-helloworld-1:
    image: hsz1273327/js-server:restful_c0
    networks:
      - rest_test
  rest-helloworld-2:
    image: hsz1273327/js-server:restful_c0
    networks:
      - rest_test

  rest-helloworld-3:
    image: hsz1273327/js-server:restful_c0
    networks:
      - rest_test

  http-reverse-proxy:
    image: nginx:alpine
    networks:
      - rest_test
    ports:
      - 5000:5000
    depends_on:
      - rest-helloworld-1
      - rest-helloworld-2
      - rest-helloworld-3
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d


networks:
  rest_test:
