version: "3.6"
services:
  ws-api:
    build: ./server
    image: hsz1273327/js-server:websocket
    ports:
      - 3000:3000
    networks:
      - rest_test
  http-reverse-proxy:
    image: nginx:alpine
    networks:
      - rest_test
    ports:
      - 8000:8000
    depends_on:
      - ws-api
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d

networks:
  rest_test:
